#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/dfs
#
# IDENTIFICATION
#    src/backend/storage/dfs/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/dfs
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	dfs_option.o \
	ufs.o \
	ufs_connection.o

include $(top_srcdir)/src/backend/common.mk
